spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: onboarding-mcp-server
        version: 0.0.1
        type: SYNC
        capabilities:
          tool: true
          resource: true
          prompt: true

app:
  docs:
    path: ./rideflex-docs

logging:
  pattern:
    console: ""
  file:
    name: /tmp/onboarding-mcp-server.log
